config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


# Member
get 'members' => 'members#index', as: :members
get 'members/new' => 'members#new', as: :new_member
get 'members/:id' => 'members#show', as: :member

post 'members' => 'members#create'

get 'members/:id/edit' => 'members#edit', as: :edit_member
patch 'members/:id' => 'members#update'

delete 'members/:id' => 'members#destroy'

# Team
get 'teams' => 'teams#index', as: :teams
get 'teams/new' => 'teams#new', as: :new_team
get 'teams/:id' => 'teams#show', as: :team

post 'teams' => 'teams#create'

get 'teams/:id/edit' => 'teams#edit', as: :edit_team
patch 'teams/:id' => 'teams#update'

delete 'teams/:id' => 'teams#destroy'


# Score
get 'scores' => 'scores#index', as: :scores
get 'scores/new' => 'scores#new', as: :new_score
get 'scores/:id' => 'scores#show', as: :score

post 'scores' => 'scores#create'

get 'scores/:id/edit' => 'scores#edit', as: :edit_score
patch 'scores/:id' => 'scores#update'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :team
end

app/models/score.rb
class Score < ApplicationRecord
  has_one :team

end

app/models/team.rb
class Team < ApplicationRecord
  has_many :members
  belongs_to :score
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  def index
    @members = Member.all
  end

  def show
    @member = Member.find(params[:id])
  end

  def new
    @member = Member.new
  end

  def create
      @member = Member.new(member_params)
    if @member.save
      redirect_to member_path(@member.id)
    else
         render 'new'
    end

  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update_attributes(member_params)
      redirect_to member_path(@member.id)
    else
      render 'edit'
    end
  end

  def destroy
    @member = Member.find(params[:id])

    @member.destroy

    redirect_to members_path
  end

  private

  def member_params
    params.require(:member).permit(:name,:age,:email_adress,:capitain,:team_id)
  end




end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def index
    @scores = Score.all
  end

  def show
    @score = Score.find(params[:id])
  end

  def new
    @score = Score.new
  end



  def create
    @score = Score.new(score_params)

    if @score.save
      redirect_to score_path(@score.id)
    else
      render 'new'
    end

  end

  def edit
    @score = Score.find(params[:id])
  end


  def update
    @score = Score.find(params[:id])
    if @score.update_attributes(score_params)
      redirect_to score_path(@score.id)
    else
      render 'edit'
    end
  end



  private
  def score_params
    params.require(:score).permit(:concept,:style,:git,:user_friendly)
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

def index
  @teams = Team.all
end


def show
  @team = Team.find(params[:id])
end

def new
  @team = Team.new
end

def create
  score = Score.create!({concept: 0, style: 0, git: 0, user_friendly: 0})

  @team = Team.new(team_params)
  @team.score = score

  if @team.save
    redirect_to team_path(@team.id)
  else
    render 'new'
  end
end

def edit
  @team = Team.find(params[:id])
end

def update
  @team = Team.find(params[:id])
  if @team.update_attributes(team_params)
    redirect_to team_path(@team.id)
  else
    render 'edit'
  end
end

def destroy
  @team = Team.find(params[:id])

  @team.destroy

  redirect_to teams_path
end


private
def team_params
  params.require(:team).permit(:name,:description,:code_link,:logo,:score_id)
end

end

# def create
#     @member = Member.new(member_params)
#   if @member.save
#     redirect_to member_path(@member.id)
#   else
#        render 'new'
#   end
#
# end
#
#
#
#
# private
#
# def member_params
#   params.require(:member).permit(:name,:age,:email_adress,:capitain,:team_id)
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TMC</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <hr />
  <%= link_to "Back to Homepage", teams_path %>
  <footer>
    <hr />
    <p>&#10084; By Jiamei Wu</p>
  </footer>

  </body>
</html>

app/views/members/_form.html.erb
<%= form_for @member do |f| %>
<hr>
  <%= f.label :name %>
  <%= f.text_field :name %>
<br />
  <%= f.label :age %>
  <%= f.number_field :age %>
<br />
  <%= f.label :Email_Address %>
  <%= f.text_field :email_address %>
<br />
  <%= f.label :captain %>
  <%= f.check_box :capitain %>
<br />
  <%= f.label :team %>
  <%= f.collection_select(:team_id, Team.all, :id, :name) %>
<br />

  <%= f.submit %>
<% end %>

app/views/members/edit.html.erb
<h2>Edit Member Information</h2>
<%= render 'form' %>

app/views/members/index.html.erb
<h1>List of Members</h1>


<ul>
  <% @members.each do |member| %>
    <li>

    <p><%= link_to member.name, member_path(member.id) %></p>





    </li>

  <% end %>

</ul>

<hr />
<h1>Create Members for Your Team</h1>
<br />
<%= link_to 'Add a Member', new_member_path %>

app/views/members/new.html.erb
<h2>Add A New Member</h2>
<%= render 'form' %>

app/views/members/show.html.erb
<h2>Member Information</h2>

<ul>
  <li>Name: <%= @member.name %></li>
  <li>Age: <%= @member.age %></li>
  <li>Email Address: <%= mail_to @member.email_address %></li>
  <li>Position: <%= "Team member" if @member.capitain; "Captain" %>
  </li>
  <li>Team: <%= link_to "#{@member.team.name}", team_path(@member.team.id) %>


  </li>
</ul>

<hr />
<%= link_to 'Edit', edit_member_path(@member.id) %>
<%= link_to 'Delete', member_path(@member.id), method: :delete, data:{confirm: "Are you sure?" } %>
<hr />
<%= link_to 'Back', members_path %>

app/views/scores/_form.html.erb
<%= form_for @score do |f| %>
<hr />
<%= f.label :concept %>
<%= f.number_field :concept %>
<br />
<%= f.label :style %>
<%= f.number_field :style %>
<br />
<%= f.label :git %>
<%= f.number_field :git %>
<br />
<%= f.label :user_friendly %>
<%= f.number_field :user_friendly %>
<br />
<%= f.submit %>


<% end %>

app/views/scores/edit.html.erb
<h2>Edit Score</h2>
<%= render 'form' %>

app/views/scores/index.html.erb
<h1>List of Scores</h1>

<% @scores.each do |score| %>



<ul>
  <li>

  <b>Team Name:</b> <%= score.team.name %> &nbsp;

  <b>Final Score:</b><%= score.concept + score.style + score.git + score.user_friendly %>

  <%= link_to '(More information)', score_path(score.id) %>

  </li>

</ul>

<% end %>

app/views/scores/new.html.erb
<h2>Add Scores</h2>
<%= render 'form' %>

app/views/scores/show.html.erb
<h2>Score Information</h2>


<h3>Team Name: <%= link_to @score.team.name, team_path(@score.team.id)  %></h3>

<h4>Total Score: <%= @score.concept + @score.style + @score.git + @score.user_friendly %></h4>

<ul>
  <li>Concept: <%= @score.concept  %></li>
  <li>Style: <%= @score.style %></li>
  <li>Git: <%= @score.git %></li>
  <li>User Friendly: <%= @score.user_friendly%></li>
</ul>

<hr />
<%= link_to 'Edit Scores', edit_score_path(@score.id) %>
<hr />
<%= link_to 'Check List of Scores', scores_path %>